// Decoder robustness, without a browser.
//
// The QR code is generated by the very function the labels page uses, then
// "photographed": 3D projection of the tilted label, inverse homography and
// bilinear sampling. That is what distinguishes a photo taken at an angle from
// a merely rotated image — and it is exactly the case pure-JavaScript decoders
// cannot handle.
import { readFileSync } from 'node:fs';
import { beforeAll, describe, expect, it } from 'vitest';
import { prepareZXingModule } from 'zxing-wasm/reader';
import { decodeQrCode, type PixelBuffer } from './qr-decoding';
import { qrCodeMatrix, qrCodeSvg } from './qr-generation';

const FIRST_NAME = 'Léa';

beforeAll(async () => {
  // Nothing to download under Node: hand the binary over directly.
  const wasmBinary = readFileSync(
    new URL('../node_modules/zxing-wasm/dist/reader/zxing_reader.wasm', import.meta.url),
  );
  await prepareZXingModule({ overrides: { wasmBinary }, fireImmediately: true });
});

// --- Fake photo factory -----------------------------------------------------

interface Degradations {
  /** Side of the label in pixels, before projection. */
  size?: number;
  /** Tilt of the label away from the lens plane. */
  tiltX?: number;
  tiltY?: number;
  /** Rotation within the image plane. */
  rotation?: number;
  width?: number;
  height?: number;
}

type Corner = readonly [number, number];

/** Crisp label: black QR on white, with the mandatory 4-module quiet zone. */
function renderLabel(size: number): PixelBuffer {
  const matrix = qrCodeMatrix(FIRST_NAME);
  const modules = matrix.length;
  const cell = Math.max(2, Math.floor(size / (modules + 8)));
  const quietZone = 4 * cell;
  const width = modules * cell + quietZone * 2;

  const data = new Uint8ClampedArray(width * width * 4).fill(255);
  for (const [row, line] of matrix.entries()) {
    for (const [column, dark] of line.entries()) {
      if (!dark) continue;
      for (let dy = 0; dy < cell; dy++) {
        for (let dx = 0; dx < cell; dx++) {
          const p = ((quietZone + row * cell + dy) * width + quietZone + column * cell + dx) * 4;
          data[p] = 0;
          data[p + 1] = 0;
          data[p + 2] = 0;
        }
      }
    }
  }
  return { data, width, height: width };
}

/** Label corners after 3D rotation and perspective projection. */
function projectedCorners(size: number, degX: number, degY: number, rotation: number): Corner[] {
  const a = (degX * Math.PI) / 180;
  const b = (degY * Math.PI) / 180;
  const focal = 2.2;
  const distance = size * focal;
  const half = size / 2;
  const spin = (rotation * Math.PI) / 180;

  const corners: Corner[] = [
    [-half, -half],
    [half, -half],
    [half, half],
    [-half, half],
  ];

  return corners.map(([x, y]): Corner => {
    const yTilted = y * Math.cos(a);
    const zTilted = y * Math.sin(a);
    const xTurned = x * Math.cos(b) + zTilted * Math.sin(b);
    const zTurned = -x * Math.sin(b) + zTilted * Math.cos(b);
    const k = (focal * size) / (distance + zTurned);
    const px = xTurned * k;
    const py = yTilted * k;
    return [px * Math.cos(spin) - py * Math.sin(spin), px * Math.sin(spin) + py * Math.cos(spin)];
  });
}

/** Unit square → quadrilateral homography (Heckbert), returned inverted. */
function inverseHomography(quad: Corner[]): number[][] {
  const [c0, c1, c2, c3] = quad as [Corner, Corner, Corner, Corner];
  const [x0, y0] = c0;
  const [x1, y1] = c1;
  const [x2, y2] = c2;
  const [x3, y3] = c3;

  const dx1 = x1 - x2;
  const dy1 = y1 - y2;
  const dx2 = x3 - x2;
  const dy2 = y3 - y2;
  const den = dx1 * dy2 - dx2 * dy1;
  const g = ((x0 - x1 + x2 - x3) * dy2 - dx2 * (y0 - y1 + y2 - y3)) / den;
  const h = (dx1 * (y0 - y1 + y2 - y3) - (x0 - x1 + x2 - x3) * dy1) / den;

  const a = x1 - x0 + g * x1;
  const b = x3 - x0 + h * x3;
  const c = x0;
  const d = y1 - y0 + g * y1;
  const e = y3 - y0 + h * y3;
  const f = y0;

  const det = a * (e - f * h) - b * (d - f * g) + c * (d * h - e * g);
  return [
    [(e - f * h) / det, (c * h - b) / det, (b * f - c * e) / det],
    [(f * g - d) / det, (a - c * g) / det, (c * d - a * f) / det],
    [(d * h - e * g) / det, (b * g - a * h) / det, (a * e - b * d) / det],
  ];
}

/** Pastes the label into a photo, projecting it. */
function photograph(degradations: Degradations = {}): PixelBuffer {
  const { size = 500, tiltX = 0, tiltY = 0, rotation = 0 } = degradations;
  const width = degradations.width ?? 3000;
  const height = degradations.height ?? 2000;

  const label = renderLabel(size);
  const cx = Math.round(width * 0.72);
  const cy = Math.round(height * 0.66);
  const quad = projectedCorners(size, tiltX, tiltY, rotation).map(([x, y]): Corner => [
    x + cx,
    y + cy,
  ]);
  const inverse = inverseHomography(quad);

  // Flat background: the table the work is lying on.
  const data = new Uint8ClampedArray(width * height * 4).fill(255);
  for (let i = 0; i < width * height; i++) {
    data[i * 4] = 200;
    data[i * 4 + 1] = 184;
    data[i * 4 + 2] = 154;
  }

  const xs = quad.map(([x]) => x);
  const ys = quad.map(([, y]) => y);
  const left = Math.max(0, Math.floor(Math.min(...xs)));
  const right = Math.min(width, Math.ceil(Math.max(...xs)));
  const top = Math.max(0, Math.floor(Math.min(...ys)));
  const bottom = Math.min(height, Math.ceil(Math.max(...ys)));

  const SUPERSAMPLE = 2; // 2×2 samples per pixel, to limit aliasing
  for (let y = top; y < bottom; y++) {
    for (let x = left; x < right; x++) {
      let sum = 0;
      let taken = 0;
      for (let sy = 0; sy < SUPERSAMPLE; sy++) {
        for (let sx = 0; sx < SUPERSAMPLE; sx++) {
          const px = x + (sx + 0.5) / SUPERSAMPLE;
          const py = y + (sy + 0.5) / SUPERSAMPLE;
          const w = inverse[2]![0]! * px + inverse[2]![1]! * py + inverse[2]![2]!;
          const u = (inverse[0]![0]! * px + inverse[0]![1]! * py + inverse[0]![2]!) / w;
          const v = (inverse[1]![0]! * px + inverse[1]![1]! * py + inverse[1]![2]!) / w;
          if (u < 0 || u >= 1 || v < 0 || v >= 1) continue;
          sum += sample(label, u, v);
          taken++;
        }
      }
      if (taken === 0) continue;
      const coverage = taken / (SUPERSAMPLE * SUPERSAMPLE);
      const value = sum / taken;
      const p = (y * width + x) * 4;
      for (let k = 0; k < 3; k++) {
        data[p + k] = data[p + k]! * (1 - coverage) + value * coverage;
      }
    }
  }
  return { data, width, height };
}

/** Bilinear sampling of the red channel (the label is greyscale). */
function sample(image: PixelBuffer, u: number, v: number): number {
  const fx = u * (image.width - 1);
  const fy = v * (image.height - 1);
  const ix = Math.floor(fx);
  const iy = Math.floor(fy);
  const tx = fx - ix;
  const ty = fy - iy;
  const ix2 = Math.min(image.width - 1, ix + 1);
  const iy2 = Math.min(image.height - 1, iy + 1);
  const at = (y: number, x: number) => image.data[(y * image.width + x) * 4] ?? 255;
  return (
    at(iy, ix) * (1 - tx) * (1 - ty) +
    at(iy, ix2) * tx * (1 - ty) +
    at(iy2, ix) * (1 - tx) * ty +
    at(iy2, ix2) * tx * ty
  );
}

/** Renders a crisp, unprojected label for an arbitrary first name. */
function flatLabel(text: string): PixelBuffer {
  const matrix = qrCodeMatrix(text);
  const modules = matrix.length;
  const cell = 8;
  const quietZone = 4 * cell;
  const width = modules * cell + quietZone * 2;
  const data = new Uint8ClampedArray(width * width * 4).fill(255);
  for (const [row, line] of matrix.entries()) {
    for (const [column, dark] of line.entries()) {
      if (!dark) continue;
      for (let dy = 0; dy < cell; dy++) {
        for (let dx = 0; dx < cell; dx++) {
          const p = ((quietZone + row * cell + dy) * width + quietZone + column * cell + dx) * 4;
          data[p] = 0;
          data[p + 1] = 0;
          data[p + 2] = 0;
        }
      }
    }
  }
  return { data, width, height: width };
}

// --- Tests ------------------------------------------------------------------

describe('QR round trip', () => {
  it.each(['Léa', 'Noé', 'Chloé B', 'Youssef', 'Marie-Claire', "Jean-Baptiste O'Neil"])(
    'encodes and reads back "%s" without losing accents',
    async (firstName) => {
      await expect(decodeQrCode(flatLabel(firstName))).resolves.toBe(firstName);
    },
  );
});

describe('photo taken at an angle', () => {
  // A hand-held photo is almost always slightly tilted: that is the normal
  // case, not the edge case.
  it.each([0, 15, 25, 35, 45])('decodes a %i° tilt on one axis', async (degrees) => {
    await expect(decodeQrCode(photograph({ tiltX: degrees }))).resolves.toBe(FIRST_NAME);
  });

  it.each([15, 25, 35])('decodes a %i° tilt on two axes', async (degrees) => {
    await expect(decodeQrCode(photograph({ tiltX: degrees, tiltY: degrees * 0.6 }))).resolves.toBe(
      FIRST_NAME,
    );
  });

  it('decodes a photo both tilted and rotated', async () => {
    await expect(decodeQrCode(photograph({ tiltX: 30, tiltY: 15, rotation: 25 }))).resolves.toBe(
      FIRST_NAME,
    );
  });
});

describe('photo rotated within its plane', () => {
  it.each([40, 90, 135, 180])('decodes a %i° rotation', async (degrees) => {
    await expect(decodeQrCode(photograph({ rotation: degrees }))).resolves.toBe(FIRST_NAME);
  });
});

describe('small label in a large photo', () => {
  it.each([500, 300, 200, 150])('decodes a %i px label inside 3000×2000', async (px) => {
    await expect(decodeQrCode(photograph({ size: px }))).resolves.toBe(FIRST_NAME);
  });

  it('decodes a 250 px label tilted 30°', async () => {
    await expect(decodeQrCode(photograph({ size: 250, tiltX: 30, tiltY: 15 }))).resolves.toBe(
      FIRST_NAME,
    );
  });
});

describe('accepted limits', () => {
  // No decoder tested handles this. The test documents the limit: if one day it
  // starts passing, that is good news to notice, not a regression to fix.
  it('does not decode beyond a 60° tilt', async () => {
    await expect(decodeQrCode(photograph({ tiltX: 65 }))).resolves.toBe('');
  });
});

describe('qrCodeSvg', () => {
  it('produces a scalable SVG', () => {
    const svg = qrCodeSvg('Léa');
    expect(svg.startsWith('<svg')).toBe(true);
    expect(svg).toContain('viewBox');
    expect(svg.trimEnd().endsWith('</svg>')).toBe(true);
  });
});
